apiVersion: batch/v1
kind: Job
metadata:
  name: olake-source-check
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      restartPolicy: Never
      volumes:
        - name: tmpl
          secret:
            secretName: REPLACEME_SOURCE_SECRET
        - name: work
          emptyDir: {}

      initContainers:
        - name: render-config
          image: busybox:1.36
          command: ["sh","-c"]
          args:
            - |
              set -e
              mkdir -p /work/logs
              cp /tmpl/source.json /work/source.json
          volumeMounts:
            - name: tmpl
              mountPath: /tmpl
              readOnly: true
            - name: work
              mountPath: /work

      containers:
        - name: discover
          image: olakego/source-postgres:latest
          args:
            - "discover"
            - "--config"
            - "/config/source.json"
          volumeMounts:
            - name: work
              mountPath: /config